on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 🧰
        run: |
          npm ci
          npm link @angular/cli

      - name: Build 🔨
        run: |
          ng build --output-path build --base-href /${{ github.event.repository.name }}/
          cp build/index.html build/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
